### ISSUE TITLE
Setup working CI

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-ceq#1]
We need to test and deploy this repo continuously.

We can do that by using circleci from the openfisca org.
According to @sandcha (thanks !) this can be done following:
- Steps to move to circleci v2 configuration file ; see commits (https://github.com/openfisca/openfisca-tunisia/pull/66)
- Steps to link the repository, circleci, pypi... (https://github.com/openfisca/extension-template/pull/15#issue-186037052)
 - circleci official documentation like : https://circleci.com/docs/2.0/migrating-from-1-2/

**Comment by benjello** [comment]
@sandcha close this whenever you think so.

**Comment by sandcha** [comment]
OpenFisca-CEQ  0.1.0  tagged and published on pypi by openfisca-bot 🎉   
All links seem ok (github/circleci/pypi/openfisca-bot).

This sets a working CI and closes the issue.
> Later CircleCI configuration could be improved; this mainly to extract `check_version_and_changelog` tag outside build tags and by ignoring tests in `has-functional-changes.sh` (`tests/*` should be in `IGNORE_DIFF_ON`).
