### ISSUE TITLE
Computing unit cost estimates for health and education services

### ISSUE THREAD

**Issue by leoczajka** [openfisca/openfisca-ceq#15]
@Mouksit : J'ai lu la note que tu nous avais envoyé concernant la méthode de calcul pour les transferts d'éducation et de santé. Est-ce que tu pourrais juste m'éclairer sur ce graph ? Comment est obtenue la courbe dite Lorenz ici ? Les 2 concentrations curve se basent-elles sur d'elle pour ajouter les transferts ? 
Merci !
<img width="476" alt="lorenz_educ_sen" src="https://user-images.githubusercontent.com/41026632/53033911-724bd800-3472-11e9-9fd7-2368a2cd4b57.png">

**Comment by Al-mouksit** [comment]
@Leocza  Oui bien sûr!

La courbe le Lorenz est le cumul en % de la conso par déciles   (déciles ordonnés selon la conso).

La courbe de concentration des transferts de l'éducation (method 1 par exemple) est le cumul en % des transferts de l'éducation par déciles (déciles toujours ordonnés selon la conso).

Si ce n'est pas claire, on peut échanger sur skype ou slack!

**Comment by leoczajka** [comment]
ok et du coup :
_ les courbes vertes et violettes sont obtenues en ajoutant à cette conso les transferts ?
_ l'effet redistributif est particulièrement prononcé pour la côte d'Ivoire, as-tu utilisé le revenu ou la conso ? 
_ tout cela me fait penser qu'il sera intéressant de calculer les ratio conso avant/après transfert, pour la population totale et aussi par niveau de revenu. 
Merci !

**Comment by Mouksit** [comment]
Hello @Leocza,

Quelques éléments de réponses:

_ les courbes vertes et violettes sont obtenues en ajoutant à cette conso les transferts ?

>Non juste le cumul des montants des transferts en %. Mais l'interprétation revient à la même chose que d'ajouter les transferts à la conso il me semble. Je n'ai pas essayé mais la différence est au niveau graphique. Généralement la courbe les courbes de concentration sont très proches (donc moins nette) lorsqu'on opte pour l'option que tu proposes. Mais dans tous les cas on peut le faire aussi.

_ l'effet redistributif est particulièrement prononcé pour la côte d'Ivoire, as-tu utilisé le revenu ou la conso ?

>J'ai utilisé la conso.

_ tout cela me fait penser qu'il sera intéressant de calculer les ratio conso avant/après transfert, pour la population totale et aussi par niveau de revenu.

>En effet bonne idée! Mais juste avoir à l'esprit que la note, c'est surtout pour l'estimation des coûts unitaires. Une analyse d'incidence approfondie sera faite plus tard.

**Comment by Mouksit** [comment]
Au fait @Leocza , je commence à comprendre tes interrogations. Il est en effet plus pertinent de faire la Lorenz de la conso avant transfert parce qu'en prenant la console tot il n'est pas facile d'interpréter. Je vais reprendre et ajouter ce que tu suggères (ratio console avant/après tranferts)
