### ISSUE TITLE
corporate income tax 

### ISSUE THREAD

**Issue by leoczajka** [openfisca/openfisca-ceq#2]
@asrobi @benjello @leaamb La corporate income tax fait partie du programme CEQ , mais comment allons-nous gérer cet aspect ? En re-distribuant l'aggrégat macro (dispo notamment pour la Cote d'Ivoire) ? Mais du coup sur qui exactement  -- étant donné que seules les entreprises formelles paient cet impôt, mais que plusieurs entreprises formelles engagent des gens informellement ?

**Comment by benjello** [comment]
Je pense qu'il faut faire des hypothèses extrêmes et voir l'ampleur de l'effet.

**Comment by leoczajka** [comment]
Ok. Le problème est que le le secteur informel est tellement massif (plus de 90% des personnes en age de travailler en côte d'Ivoire par exemple) que nous allons avoir des difficultés similaires pour redistribuer le fardeau fiscal sur un sous-ensemble des ménages pour tous ces impôts dont on ne sait pas exactement qui les paie, ex en côte d'ivoire : la taxe d'habitation et les droits de douanes.

**Comment by benjello** [comment]
Pour les droits de douane, il faudrait pouvoir déjà séparer ce qui va à la consommation finale et ce qui va alimenter les intrants. Et en toute rigueur il faudrait une matrice input-output et des règles d'incidence pour calculer l'impact de ces derniers. Bref, il faut voir ce que recouvre ces droits et faire au mieux en prenant des cas limites. 

Pour la taxe d'habitation, elle doit être recouvrée pour certains types de logements et en milieu urbain donc on devrait pouvoir la distribuer pas trop mal.

**Comment by asrobi** [comment]
Oui, il faudra des matrices input-output pour prendre en compte les effets indirects des taxes indirectes. J'ai celle du Sénégal, je vais voir si ce que je peux trouver pour le Mali et la Côte d'Ivoire.
Pour la règle d'incidence, je propose que l'on fasse l'hypothèse assez classique que les taxes indirectes sont supportées par les consommateurs.
Pour la corporate income tax... je ne sais pas ce qu'on peut en faire. J'aurais tendance à faire l'hypothèse qu'elle est supportée par les détenteurs de capital formel. Mais je ne suis pas sûre que l'on dispose de cette info dans toutes les enquêtes. Pour le Sénégal, les individus peuvent déclarer des revenus hors emploi et hors transferts mais il n'y a qu'une seule "case" et il doivent donc choisir dans une liste la principale source (commissions, honoraires, pension de retraite, pension d'invalidité, revenus locatifs, revenus d'actions/obligations). Du coup s'ils ont plus qu'une source de revenus hors emploi et hors transferts, pas possible de les déclarer tous, ce qui fait que tous ces revenus sont sous-déclarés par "design" du questionnaire.

**Comment by benjello** [comment]
@Leocza : je te laisse rapatrier les infos pertinentes de ces échanges dans un lieu plus apporprié (wiki, issue dans un pays donné) et de fermer cette issue quand tu auras fini car il n'y a plus à mon sens d'action à accomplir dans ce repo-ci.

**Comment by leoczajka** [comment]
@benjello il me semble que ne suis pas autorisé à modifier le wiki, peux-tu m'aider ?

**Comment by benjello** [comment]
@Leocza Done !

**Comment by benjello** [comment]
@Leocza peut-on fermer ?
