### ISSUE TITLE
Rewrite welcome README.md page

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-ceq#31]
Many things to do.
 - [ ] desciption of the project
 - [ ] python3 only

**Comment by benjello** [comment]
@sandcha: what we have on this README.md page is clearly outadted. Where can i find a more up to date template ? Thanks !

**Comment by sandcha** [comment]
The thing is, we might need to improve them on Core etc. as well.
I would use [openfisca-france README](https://github.com/openfisca/openfisca-france/blob/master/README.md) but, follow the introduction by defining the user profile(s)/what this repository helps them to do before listing technical instructions (as in [the doc introduction](https://openfisca.org/doc/index.html) and [openfisca-aotearoa](https://github.com/ServiceInnovationLab/openfisca-aotearoa/blob/master/README.md)).

**Comment by benjello** [comment]
Fixed by #32
